
Plug 'slim-template/vim-slim'
on_ft = ['slim']


Plug 'zyphrus/denite-git.nvim'
depends = ['denite.nvim']


Plug 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']


Plug 'python-mode/python-mode'
on_ft = ['python']
hook_add = '''
let g:pymode_rope = 0
let g:pymode_rope_lookup_project = 0
'''


Plug 'jmcantrell/vim-virtualenv'
on_ft = ['python']


Plug 'Shougo/deoplete-rct'
on_ft = 'ruby'


Plug 'zchee/deoplete-jedi'
on_ft = ['python']


Plug 'mattn/emmet-vim'
on_ft = ['html']


Plug 'Chiel92/vim-autoformat'
on_ft = ['javascript']


Plug 'digitaltoad/vim-pug'
on_ft = ['jade', 'pug']


Plug 'Shougo/deoplete-rct'
on_ft = ['ruby']
build = 'gem install rcodetools'


Plug 'rhysd/vim-textobj-ruby'
on_ft = ['ruby']


Plug 'vim-ruby/vim-ruby'
on_ft = ['ruby']


Plug '5t111111/denite-rails'
on_ft = ['ruby', 'erb']
hook_add='''
nnoremap [rails]r :Denite<Space>rails:
nnoremap <silent> <Space>r :<C-u>Denite<Space>rails:dwim<Return>
nnoremap <silent> <Space>rm :<C-u>Denite<Space>rails:model<Return>
nnoremap <silent> <Space>rc :<C-u>Denite<Space>rails:controller<Return>
nnoremap <silent> <Space>rv :<C-u>Denite<Space>rails:view<Return>
nnoremap <silent> <Space>rh :<C-u>Denite<Space>rails:helper<Return>
nnoremap <silent> <Space>rr :<C-u>Denite<Space>rails:test<Return>
'''


Plug 'dag/vim-fish'
on_ft = ['fish']


Plug 'ponko2/deoplete-fish'
on_ft = ['fish']


Plug 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'jsx']

